### PR TITLE
Misc UI feature updates

### PR DESCRIPTION
**Pull request by smmzhu**
PR for #13 

Updates:
- typewriter cycles through a series of texts
- ~~nav bar on top is colored and styled~~
- down arrow is updated

### CODE REVIEW

**Comment by rohankumar2025** [comment]
I like everything but im not rly sure about the navbar styling i kinda feel like it looks kinda wonky but a second opinion may be good here

**Comment by rohildshah** [comment]
Yeah I can second the navbar point - sort of preferred the previous version. Also typewriter text doesn't show up for me? Missing on main as well.

**Comment by smmzhu** [comment]
Ok I'll change back the nav bar for now — I'm still not super sold on how it looks right now but I'll figure it out in a PR maybe later

**Review by rohankumar2025 — APPROVED** [review]
lgtm

**Pull request merged**
